### ISSUE TITLE
Add a 'replace session with current one' button

### ISSUE THREAD

**Issue by Antoine-Patel** [ReDEnergy/SessionSync#1]
[**note**] Please feel free to implement the general idea, if it's
accepted, your own way and not necessarily as I see it -- I'm just
throwing ideas.

[**description**] Add a button that replaces a session with the current
session ( something similar to the 'Add current tab' button ).

[**rationale**] Creating a new session, then deleting the one user
wants to replace, then renaming it with the deleted session's name is
slow and tedious.

**Comment by Backfighter** [comment]
This would be a really awesome feature! What made you remove it from the 1.1 milestone?
Will it make it into future releases?

**Comment by ReDEnergy** [comment]
It will be available in 2.0. I had to rewrite almost everything again and thus 1.1 made little sense. I will provide most of the features requested in 2.0. I hope to launch it later this month. I already started implementing this feature (sadly is still disabled in the latest dev version). You can download the latest version (unsigned) from the first page. It's 100% stable but there are still some missing features that need to be added.

**Comment by ReDEnergy** [comment]
Feature added as of v.2.0.1
