### ISSUE TITLE
HTML export

### ISSUE THREAD

**Issue by rayman89** [ReDEnergy/SessionSync#10]
I wanted to request the feature to be able to export the session as an html file or to be able to show the session on a tab for easy access to the webpages you have. It's easier, for me at least, to go back and forth between tabs than pop up menus and also easier to remember to check an open tab than items on a menu.

**Comment by ReDEnergy** [comment]
I plan to add support for a full-page UI that might as well be opened in a new tab. I will take this into consideration and provide some user preferences for the UI.

**Comment by rayman89** [comment]
No need to apologize. Thanks for taking user requests in mind, answering quickly and for creating and maintaining the add-on.

**Comment by ReDEnergy** [comment]
Feature implemented into the WebExtensions port. Thanks for the feedback.
