### ISSUE TITLE
Restoring a session reverses the order

### ISSUE THREAD

**Issue by charlieok** [ReDEnergy/SessionSync#110]
I accidentally deleted a session. Fortunately there's a button to restore it (thank you!) so I did that. But the order of items in the restored session was reversed.

After noticing this behavior a few times, I've started re-deleting and re-restoring when this happens, to return to the original order of items.

**Comment by ReDEnergy** [comment]
![image](https://user-images.githubusercontent.com/1395510/196044524-e33915b9-9009-4e14-bd64-036fd2b7c4a1.png)
Maybe this helps from the options.

**Comment by charlieok** [comment]
ah, thank you; I hadn't seen that option
