### ISSUE TITLE
How to export all my saved sessions

### ISSUE THREAD

**Issue by BigBadDens** [ReDEnergy/SessionSync#112]
Hello, 

I'd like to know something : 

If I log in Firefox with my Firefox account and install the extension once again but on a new computer, will I find back all my saved sessions that were on my first computer ?

Thank you for your feedback.

**Comment by ReDEnergy** [comment]
Yeah, as long as you have Bookmarks synced on the Firefox account profile all saved sessions should be available on the second PC as well. Also, exporting and importing the Bookmarks will do the same, but it's better to just have them synced using Firefox account.
