### ISSUE TITLE
URGENT: Extension icon missing, can't restore tabs

### ISSUE THREAD

**Issue by AndrewDillon** [ReDEnergy/SessionSync#122]
Extension enabled.

Closed Firefox then reopened.

Tabs not restored.
Noticed extension icon missing from toolbar (and menu - can't remember if usually there), and Ctrl+Shift+F opens different extension.
Extension still enabled.

How can I open widget and restore tabs?

Thanks!

**Comment by ReDEnergy** [comment]
There's a chance another Firefox addon took over that specific shortcut. If you didn't have any history sessions saved and only bookmarked sessions, reinstalling the addon might be the best solution because all the bookmarks will remain there.

**Comment by ReDEnergy** [comment]
Closing as support moved to mailing.
