### ISSUE TITLE
Session Sync stores only active Window

### ISSUE THREAD

**Issue by the42** [ReDEnergy/SessionSync#15]
Session sync should store all open windows not only the active one

**Comment by M-G-ARC** [comment]
Agree this would be a great feature. Any additional features you can find to include from "tabs outliner" on chrome would be welcome.

**Comment by ReDEnergy** [comment]
thanks for info. I'll take a look into it.

**Comment by CPngN** [comment]
Yes, please add the ability to save all windows.  Even if you store each window separately as one would have to do now manually.  Perhaps have a master session, with windows as sub sections.  Basically like the Session Manager plugin, but with your ability to sync and maintain sync across internet to 2 or 3 machines.  Awaiting this feature to solve all my issues with keeping access from home and work in sync when not using same laptop! Thank you!

**Comment by ReDEnergy** [comment]
Fixed in version 2.0.1
 - added option to save all windows at the same time
 - each window is stored in a separate bookmark folder
