### ISSUE TITLE
Support multiprocess firefox (electrolysis e10s)

### ISSUE THREAD

**Issue by FSMaxB** [ReDEnergy/SessionSync#18]
Please make your extension compatible with [multiprocess firefox](https://wiki.mozilla.org/Electrolysis), or if it already is, mark the metadata of the addon so that firefox knows it's compatible.

**Comment by ReDEnergy** [comment]
Mm. Thank you for pointing that out. It should definetely be but i forgot to add the description. It will be fixed by next update (next after review is completed)

**Comment by ReDEnergy** [comment]
Fixed in latest release
