### ISSUE TITLE
[Question] When will the new release be available

### ISSUE THREAD

**Issue by FSMaxB** [ReDEnergy/SessionSync#19]
From what you have written in the README, it looks to me like you have already submitted version 2 to AMO and are still waiting for the review process to be completed.

Is that correct and if yes, do you have an estimate on how long it will take until this process is finished?

**Comment by ReDEnergy** [comment]
Hi... It should be available in 2 to 3 days maximum. Sorry for the long wait.

**Comment by FSMaxB** [comment]
Thank you very much for your time and effort in creating this extension.

**Comment by ReDEnergy** [comment]
Glad that others find it useful :)

**Comment by ReDEnergy** [comment]
It's up and running now. https://addons.mozilla.org/en-US/firefox/addon/session-sync/
Sadly I might missed to add a lot of **how-to** information so if you have any question don't hesitate to ask

**Comment by FSMaxB** [comment]
Nice! Good Job!
