### ISSUE TITLE
Add a 'Merge with current session/Add all tabs' button

### ISSUE THREAD

**Issue by Antoine-Patel** [ReDEnergy/SessionSync#2]
[**note**] Please feel free to implement the general idea, if it's
accepted, your own way and not necessarily as I see it -- I'm just
throwing ideas.

[**description**] Add a button that adds all tabs ( merges current
session ) to an existing session ( something similar to the 'Add
current tab' button ).

[**rationale**] It can be achieved by creating a new session, then
merging its corresponding bookmark folder with the bookmark folder of
the other (target) session. But it's slow and tedious. A user with
eg. a 'read it later' session, that needs to grow whenever he finds
new interesting web pages, would benefits a lot from this feature.

**Comment by ReDEnergy** [comment]
Feature implemented in v2.0.1
  - duplicate bookmarks are ignored by default
