### ISSUE TITLE
Scrolling config sidebar on small monitors

### ISSUE THREAD

**Issue by p-friedrich** [ReDEnergy/SessionSync#22]
My laptop monitor is too small to show the whole config sidebar and it seems that this sidebar doesn't scroll with the page.

**Comment by ReDEnergy** [comment]
Hi. I'm aware of this issues. I will fix it in the next update.
For the moment you can toggle each configuration area (by pressing on its title) and thus no matter how small the resolution is you should be able to see each individual category.
I will definitely provide something friendlier in the next updates.

**Comment by p-friedrich** [comment]
Thanks for the tip. Maybe you could make this functionality more intuitive/discoverable by adding a small triangle (>) to the left of the Heading?

**Comment by ReDEnergy** [comment]
Fixed since Version 3.0 477ca83333886efc2d7ef5f5a4b1b408acd81d29
