### ISSUE TITLE
Some tabs URLs is lost when using "auto-save sessions"

### ISSUE THREAD

**Issue by naodesu** [ReDEnergy/SessionSync#26]
I have "auto-save sessions" function enabled.
When I close browser, open it again and trying to restore my last session from "History" tab sometimes I see that most of the tab URLs contain just about:blank.
It happens in like 50% situations.

Using FF 56.0.2 x86-64 on Windows 8.1
Sessions sync 2.0.2

**Comment by ReDEnergy** [comment]
Hi. I have a vague idea from where the problem might be but I expected it to happen only for a session restored without loading of all the tabs and then the browser was restarted (something that should usually happen rare). Sorry for the bad experience, I will try to fix this bug by the next release.
P.S Also thanks for the review and for the fair rating even though you had these issues that often.

**Comment by naodesu** [comment]
You mean background (unloaded) tabs? Yes, there are many of them.
Or you mean I restored tabs and immediately closed browser? I didn't do that.

**Comment by rayman89** [comment]
Maybe it's not your case but AFAIK addons cannot  restore firefox tabs like about:addons or moz-extension urls

**Comment by ReDEnergy** [comment]
Closed as it's no longer valid for the WebExtensions port.
