### ISSUE TITLE
Session is restored in reverse order

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [ReDEnergy/SessionSync#37]
No comment.

**Comment by ReDEnergy** [comment]
I know... tracking this one as well for the next release. It seems that Firefox internally actually saves the bookmarks in reverse order (even though I save them in the proper order) and when restoring they are restored properly. A fix will be available very soon.

**Comment by c-e-p-x-u-o** [comment]
Yes, really it's saved in reverse order.

**Comment by ReDEnergy** [comment]
Fixed in version 3.0.1 - 544850e
