### ISSUE TITLE
Add an help button

### ISSUE THREAD

**Issue by Antoine-Patel** [ReDEnergy/SessionSync#4]
Add a 'help' button (or link or whatever) somewhere that brings the help of your add-on.

The help is shown at first install. But then to display it again, the user needs to click the button called 'add-on page' in the add-ons manager of Firefox. It's hard to find and not very intuitive.

**Comment by ReDEnergy** [comment]
Fixed in v2.0.1
  - there's a help button in the addon-bar
  - another button can be found in the main menu of the UI
