### ISSUE TITLE
Privacy violation - full browsing history send to google

### ISSUE THREAD

**Issue by lizoha** [ReDEnergy/SessionSync#47]
WTH you use s2.googleusercontent.com/s2/favicons?domain_url to get favicons?!? You literally send our full browsing history to google! Is this privacy for you?! Are you paid for this by google?

**Comment by ReDEnergy** [comment]
Fixed as soon as you reported it. A new version is already uploaded (Version 3.0.3). No other request is made. 
I suppose it makes no sense to explain again but it was a really stupid mistake to not realize that favicons request using the google service is a serious privacy concern.
A new solution based on a local caching will be provided during the next few days.
Again, really sorry for this. I really care about privacy and this was a just stupid mistake.
