### ISSUE TITLE
Double-click session name to edit it

### ISSUE THREAD

**Issue by Antoine-Patel** [ReDEnergy/SessionSync#6]
[**note**] Please feel free to implement the general idea, if it's
accepted, your own way and not necessarily as I see it -- I'm just
throwing ideas.

[**description**] Double-clicking a session name to edit it, just like
what right-clicking it and selecting the 'edit' menu item do.

[**rationale**] It's easier. When you plan to rename every single
session you create it matters.Plus double-clicking some text that can
be edited makes sense and is a commonly used way to do it across apps.

**Comment by ReDEnergy** [comment]
Fixed in v2.0.1
  - Also works for bookmarks but there's a side-effect bug - the link will be opened 2 times
