### ISSUE TITLE
Focus "Title" text field in edit session popup (~form)

### ISSUE THREAD

**Issue by Antoine-Patel** [ReDEnergy/SessionSync#7]
[**description**] When right-clicking a session name and choosing the
'edit' menu-item, no text field is focused. User needs to click in a
text field before typing. The focus should be on the 'Title' text
field (because it's the first one and the one the user most likely
wants to edit). I'd say the default title should even be pre-selected,
to be able to delete it with a single keystroke (backspace).

[**rationale**] Avoiding a uneeded extra step to perform a really
common task.

**Comment by ReDEnergy** [comment]
Fixed in v2.0.1
